	.align 2
DirectSoundWaveData_sc88_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88_organ2::
	.incbin "sound/direct_sound_samples/sc88_organ2.bin"

	.align 2
DirectSoundWaveData_sc88_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88_fretless_bass.bin"

	.align 2
DirectSoundWaveData_jv1080_slap_bass::
	.incbin "sound/direct_sound_samples/jv1080_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88_synth_bass::
	.incbin "sound/direct_sound_samples/sc88_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88_timpani::
	.incbin "sound/direct_sound_samples/sc88_timpani.bin"

	.align 2
DirectSoundWaveData_advanced_orchestra_voice_ahhs::
	.incbin "sound/direct_sound_samples/advanced_orchestra_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_electric_guitar::
	.incbin "sound/direct_sound_samples/unused_electric_guitar.bin"

	.align 2
DirectSoundWaveData_unused_sc88_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_low::
	.incbin "sound/direct_sound_samples/unknown_wood_block_low.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_high::
	.incbin "sound/direct_sound_samples/unknown_wood_block_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_kick::
	.incbin "sound/direct_sound_samples/sc88_standard_kick.bin"

	.align 2
DirectSoundWaveData_sc88_standard_snare1::
	.incbin "sound/direct_sound_samples/sc88_standard_snare1.bin"

	.align 2
DirectSoundWaveData_sc88_standard_hand_clap::
	.incbin "sound/direct_sound_samples/sc88_standard_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88_standard_snare2::
	.incbin "sound/direct_sound_samples/sc88_standard_snare2.bin"

	.align 2
DirectSoundWaveData_unknown_tom::
	.incbin "sound/direct_sound_samples/unknown_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_unknown_tambourine::
	.incbin "sound/direct_sound_samples/unknown_tambourine.bin"

	.align 2
DirectSoundWaveData_unknown_cymbal_crash::
	.incbin "sound/direct_sound_samples/unknown_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_standard_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88_standard_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_bongo::
	.incbin "sound/direct_sound_samples/sc88_bongo.bin"

	.align 2
DirectSoundWaveData_sc88_bongo_low::
	.incbin "sound/direct_sound_samples/sc88_bongo_low.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_unknown_cowbell::
	.incbin "sound/direct_sound_samples/unknown_cowbell.bin"

	.align 2
DirectSoundWaveData_unknown_djembe::
	.incbin "sound/direct_sound_samples/unknown_djembe.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_high::
	.incbin "sound/direct_sound_samples/unknown_anvil_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_bells::
	.incbin "sound/direct_sound_samples/sc88_standard_bells.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_low::
	.incbin "sound/direct_sound_samples/unknown_anvil_low.bin"

	.align 2
DirectSoundWaveData_unknown_ethnic_drum::
	.incbin "sound/direct_sound_samples/unknown_ethnic_drum.bin"

	.align 2
DirectSoundWaveData_unknown_tsuzumi::
	.incbin "sound/direct_sound_samples/unknown_tsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_48::
	.incbin "sound/direct_sound_samples/sc88_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_60::
	.incbin "sound/direct_sound_samples/sc88_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_72::
	.incbin "sound/direct_sound_samples/sc88_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_84::
	.incbin "sound/direct_sound_samples/sc88_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88_trumpet_84.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_39::
	.incbin "sound/direct_sound_samples/unknown_trombone_39.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_51::
	.incbin "sound/direct_sound_samples/unknown_trombone_51.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88_flute::
	.incbin "sound/direct_sound_samples/sc88_flute.bin"

	.align 2
DirectSoundWaveData_sc88_pick_bass::
	.incbin "sound/direct_sound_samples/sc88_pick_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_unknown_church_organ::
	.incbin "sound/direct_sound_samples/unknown_church_organ.bin"

	.align 2
DirectSoundWaveData_emu_ii_pipe_organ::
	.incbin "sound/direct_sound_samples/emu_ii_pipe_organ.bin"

	.align 2
DirectSoundWaveData_unused_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_unknown_e_piano_low::
	.incbin "sound/direct_sound_samples/unknown_e_piano_low.bin"

	.align 2
DirectSoundWaveData_unknown_e_piano_high::
	.incbin "sound/direct_sound_samples/unknown_e_piano_high.bin"

	.align 2
DirectSoundWaveData_sc88_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc88_square::
	.incbin "sound/direct_sound_samples/unused_sc88_square.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88_wind::
	.incbin "sound/direct_sound_samples/sc88_wind.bin"

	.align 2
DirectSoundWaveData_sc88_bubbles::
	.incbin "sound/direct_sound_samples/sc88_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_unused_acid_bass::
	.incbin "sound/direct_sound_samples/unused_acid_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_unknown_polysynth::
	.incbin "sound/direct_sound_samples/unknown_polysynth.bin"

	.align 2
DirectSoundWaveData_sc88_harp::
	.incbin "sound/direct_sound_samples/sc88_harp.bin"

	.align 2
DirectSoundWaveData_sc88_xylophone::
	.incbin "sound/direct_sound_samples/sc88_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88_accordion::
	.incbin "sound/direct_sound_samples/sc88_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_nyan_kaching_sound::
	.incbin "sound/direct_sound_samples/nyanCatKaching.bin"

	.align 2
DirectSoundWaveData_sd90_classical_guitar_harmonics::
	.incbin "sound/direct_sound_samples/sd90_classical_guitar_harmonics.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
